def obtener_no_repetidos(lista1, lista2):
    # Creamos un conjunto con los elementos de la primera lista para búsqueda más rápida
    conjunto1 = set(lista1)
    
    # Filtramos los elementos que no están en la primera lista
    no_repetidos = [elemento for elemento in lista2 if elemento in conjunto1]
    
    return no_repetidos

# Ejemplo de uso
campos1 = [
    "Hotel",
    "Numero Reserva",
    "Posición",
    "Numero de linea",
    "Fecha de producción  del servicio",
    "Identificador de concepto",
    "Cantidad",
    "Importe",
    "Precio 6 decimales precisión",
    "Moneda",
    "Estado de la reserva",
    "Indicador impuestos",
    "Precio transaccion",
    "Precio transacción sin impuestos",
    "Moneda de la transaccion",
    "Fecha para determinacion del cambio",
    "Cambio para la determinación de precios",
    "Tipo cargo",
    "Producido",
    "Número de Documento Comercial",
    "Reserva origen del cargo",
    "Estado cargo",
    "Anulado por",
    "Número del cargo",
    "Motivo anulación",
    "Habitación",
    "Nombre del huésped",
    "Tipo de persona que lo ocupa.",
    "Fecha cargo",
    "Hora del cargo",
    "Usuarios",
    "Impuestos incluidos",
    "Descuento %",
    "Porcentaje cliente comercial",
    "Traspasado a FI",
    "Forma de pago",
    "Base Comisión",
    "Importe Comisión",
    "Numero Reserva Tiempo Libre",
    "ID. Dispositivo",
    "Numero de ticket del TPV",
    "Marca de descuento",
    "Opción de estancia",
    "Cargo proviene de separar otros",
    "Marca anticipos contab. desde FI",
    "Nº documento",
    "Ejercicio",
    "Número de Documento Comercial_1",
    "No recalcular",
    "Movido automáticamente",
    "Movido manualmente",
    "Nº de cargo origen en linfol",
    "Sección",
    "Identificador de elemento en una sala",
    "Identificador de concepto_1",
    "Marca de descuento_1",
    "Porcentaje cliente comercial_1",
    "Precio 6 decimales precisión_1",
    "Porcentaje para el CRS",
    "Precio 6 decimales precisión_2",
    "Histórico de reservas del cargo"
]
campos2 = [
    "Hotel",
    "Numero Reserva",
    "Posición",
    "Cliente comercial",
    "Folio",
    "Identificador de concepto",
    "Descripción",
    "Fecha producción",
    "Fecha prestación",
    "Precio concepto sin impuestos",
    "Precio concepto con impuestos",
    "Cantidad",
    "Base imponible",
    "Importe de impuestos",
    "Importe",
    "Moneda",
    "Indicador impuestos",
    "Precio transaccion",
    "Precio transacción sin impuestos",
    "Moneda de la transaccion",
    "Fecha para determinacion del cambio",
    "Cambio para la determinación de precios",
    "Tipo cargo",
    "Producido",
    "Número de Documento Comercial",
    "Reserva origen del cargo",
    "Estado cargo",
    "Anulado por",
    "Número del cargo",
    "Motivo anulación",
    "Habitación",
    "Fecha cargo",
    "Hora del cargo",
    "Usuarios",
    "Impuestos incluidos",
    "Forma de pago",
    "Impuestos incluidos_1",
    "Factura a",
    "Identificador formato agrupación cargo",
    "Reserva cerrada",
    "Responsable del Folio",
    "Nombre del huésped",
    "Tipo de persona que lo ocupa.",
    "Importe Comisión",
    "Porcentaje cliente comercial",
    "Tipo de reserva (grupo)",
    "Idenficador de cupo",
    "Fecha  llegada",
    "Fecha  de salida",
    "Flag de check-in",
    "Flag de Check-out",
    "Estado de la reserva",
    "Condiciones de pago",
    "CRS",
    "Porcentaje para el CRS",
    "Importe Comisión CRS",
    "Descuento %",
    "Base Comisión",
    "Base Comisión CRS",
    "Posición de la persona dentro de la hab.",
    "Traspasado a FI",
    "Numero Reserva Tiempo Libre",
    "Identificador del Grupo de Reserva",
    "Marca de descuento",
    "ID. Dispositivo",
    "Numero de ticket del TPV",
    "Opción de estancia",
    "Es cargo de Balneario",
    "Cargo proviene de separar otros",
    "Marca anticipos contab. desde FI",
    "Nº documento",
    "Ejercicio",
    "Motivo cancelación cargo minibar",
    "Es cargo de minibar",
    "Importe de las City tax",
    "Fidelización",
    "Número de Documento Comercial_1",
    "Naturaleza concepto",
    "Interviene en Extras ?",
    "Movido automáticamente",
    "Movido manualmente",
    "Nº de cargo origen en linfol",
    "Sección",
    "Identificador de elemento en una sala",
    "Cargo de tasa especial",
    "No recalcular",
    "Empleado que contrata la OEs",
    "Empleado que anula el cargo de OE",
    "% Comisión empleado por upselling",
    "Importe comisión de upselling",
    "Oferta",
    "Se ha cambiado la descripción",
    "Histórico de reservas del cargo",
    "Moneda usada en el Hotel",
    "Moneda cabecera del folio",
    "Clasificación fiscal",
    "Cliente Fiscal",
    "Indicador impuestos_1",
    "Código de agrupación",
    "Descripción código agrupaci.",
    "Se ha cambiado la descripción_1",
    "Se ha cambiado la descripción_2",
    "Clasificación fiscal_1",
    "Número de Documento Justificante",
    "Bono",
    "Variable booleana (X=verdadero, -=falso,",
    "Motivo cambio clasificacion fiscal",
    "Tipo de habitación",
    "Sub dirección",
    "Casilla de selección",
    "Hotel_1",
    "Numero Reserva_1",
    "Posición_1",
    "Motivo del descuento",
    "Porcentaje de descuento",
    "Importe origen sin impuestos",
    "Importe origen con impuestos",
    "Observaciones del descuento",
    "Usuario que ha registrado descuento",
    "Fecha de proceso",
    "Hora de proceso",
    "ID Texto",
    "Usuario que ha separado los cargos",
    "Usuario que ha movido el cargo",
    "Posición_1_1",
    "Usuario que ha creado el registro",
    "Codigo de impuesto",
    "Linea relacionada",
    "Número de Documento Comercial_2",
    "Cambio para la determinación de precios_1",
    "Número de Factura",
    "Importe redondeo",
    "Importe redondeo_1",
    "Base imponible_1",
    "Excención Manual",
    "Motivo de exención",
    "Id de transacción",
    "Número de líneas",
    "Orden  Sala",
    "Factor (de)",
    "Factor (a)",
    "Elemento de datos Suplemtento modificaci",
    "Hu.hor.",
    "Hu.hor._1",
    "Casilla de selección_1",
    "ID Miscelaneo",
    "Res.Cargo Orig.",
    "Doc.facturación"
]


resultado = obtener_no_repetidos(campos2, campos1)

print("Elementos en la lista 2 que no están en la lista 1:")
print(resultado)

# Que guarde el resultado en un archivo de texto
with open("resultado_no_repetidos.txt", "w") as archivo:
    for elemento in resultado:
        archivo.write(f"{elemento}\n")
